### ISSUE TITLE
Cannot resolve the name of `* .domcloud.io`

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-io#11]
The name server of `domcloud.io` (New York server) cannot be resolved after 3am (UTC) on June 4th.
I've confirmed this, so I think I was influenced by the work involved: https://github.com/domcloud/domcloud-io/issues/10

```
PS C:\Users\balloon> dig domcloud.io "@8.8.8.8"

;; QUESTION SECTION:
;domcloud.io.                   IN      A
```

`domcloud.id` (Singapore server) and the website are working and you can log in to the portal from https://domcloud.id/ .
So I reported to the `domcloud-io` repository.

**Comment by willnode** [comment]
Oops. wrong firewall config. Has been fixed now?

**Comment by fu-sen** [comment]
Okay. I can see the normal display of the whole `.domcloud.io`.
It is not shown in [Status](https://stats.uptimerobot.com/AA77Xt9Jx8) and may need to be adjusted.
The issue here has been resolved so I can close it, but maybe you'll have a few days of hard work involved. 😫
May DOM Cloud continue to operate in good condition.

**Comment by willnode** [comment]
Well, technically it's still correct that it's operation. The system runs just fine, just unable to resolve to the vanity domain to domcloud.io. We may put more diagnostics later on.

**Comment by fu-sen** [comment]
I understand that it's about status. UptimeRobot can connect to the port and check, but not about working the apps.
