### ISSUE TITLE
Web SSH is not working

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-io#13]
Web SSH is currently unavailable. SSH itself can be logged in.
It occurs only on the New York server.

**Comment by willnode** [comment]
I just tested it that things seems normal to me.

It could be because of high traffic incoming to the server, so it's temporary.

**Comment by fu-sen** [comment]
No, I haven't received a response in a few days. Is this also influenced by the firewall?

**Comment by willnode** [comment]
My bad, I incorrectly read your issue.

I have fixed it.

**Comment by fu-sen** [comment]
My account was empty, so I created a new one on the New York server and confirmed this.

![スクリーンショット 2021-06-21 22 01 52](https://user-images.githubusercontent.com/5434159/122766490-91760100-d2dc-11eb-945c-0a0cbba209f7.jpg)

This is working. Thank you for your support. This issue will be closed.
