### ISSUE TITLE
Preparing for DNS migration

### ISSUE THREAD

**Issue by willnode** [domcloud/domcloud-io#17]
We recently added a new server located in Tokyo, Japan. However, it can't be used because there's no room for another free wildcard domain.

In the upcoming days, we'll implement dynamic DNS management for `domcloud.io` for all servers. This means no matter the location server you're choosing the free domain will be `domcloud.io` for all new hosts. Existing `.dom.my.id` users can still use the domain until it expires by next year. Existing `domcloud.io` should not be affected by service disruption, although it's not a guarantee.

**Comment by fu-sen** [comment]
I can confirm that it works with your fix. You will be able to close it.

**Comment by willnode** [comment]
Yeah, should be stable already.
